api:
  build: .
  command: bin/rails s -p 5000 -b 0.0.0.0
  working_dir: /api
  volumes:
    - ./api:/api
    - ./frontend:/frontend
  links:
    - postgres
  ports:
    - "5000:5000"
  environment:
    BUNDLE_JOBS: 20

frontend:
  image: tiny_api
  command: ./node_modules/ember-cli/bin/ember serve -p 4200 --live-reload-port 35729
  working_dir: /frontend
  volumes:
    - ./api:/api
    - ./frontend:/frontend
  ports:
    - "4200:4200"
    - "35729:35729"

frontendprod:
  image: tiny_api
  command: ./node_modules/ember-cli/bin/ember serve -p 9000 --live-reload-port 35729 --environment production
  working_dir: /frontend
  volumes:
    - ./api:/api
    - ./frontend:/frontend
  ports:
    - "9000:9000"
    - "35729:35729"

tests:
  image: tiny_api
  command: rake
  working_dir: /tests
  volumes:
    - ./api:/api
    - ./frontend:/frontend
    - ./tests:/tests
  links:
    - postgres
  ports:
    - "4201:4201"
    - "3001:3001"

postgres:
  image: postgres:9.5
  ports:
    - "5432"
