api:
  build: ./api
  command: bin/rails s -p 5000 -b 0.0.0.0
  working_dir: /api
  links:
    - redis
    - postgres
  environment:
    BUNDLE_JOBS: 20
    RAILS_ENV: production
    SECRET_KEY_BASE: 9df38b31acadc9c3cc97b338859068c36dc39038b3e6b087d196308fdc02a96b047997f44df11b1e14131d17f8dced71cf5a2576d089d700892bdde633885100
    RAILS_RELATIVE_URL_ROOT: '/api'
    SECRET_KEY: sk_test_GtRBEK1V5RwFJMiOgarfWny1
    PUBLISHABLE_KEY: pk_test_sQlqVzfDGPAeGYhYcxWKga2D
    API_DATABASE_USERNAME: postgres
  volumes:
    - ./api:/api
    - ./frontend/main:/frontend
    - ./frontend/modules/custom-fields:/custom-fields

frontend:
  build: ./frontend
  command: ember serve -p 4200 --environment production --live-reload false
  working_dir: /frontend
  volumes:
    - ./api:/api
    - ./frontend/main:/frontend
    - ./frontend/modules/custom-fields:/custom-fields

nginx:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
  links:
    - frontend
    - api
  ports:
    - "80:80"
