api:
  build: .
  command: bin/rails s -p 5000
  working_dir: /api
  volumes:
    - ./api:/api
    - ./frontend:/frontend
  links:
    - postgres
  ports:
    - "5000:5000"
  volumes_from:
    - bundle
  environment:
    BUNDLE_GEMFILE: /api/Gemfile
    BUNDLE_JOBS: 20
    BUNDLE_PATH: /bundle

frontend:
  build: .
  command: ./node_modules/ember-cli/bin/ember serve -p 4200 --live-reload-port 35729
  working_dir: /frontend
  volumes:
    - ./api:/api
    - ./frontend:/frontend
  ports:
    - "4200:4200"
    - "35729:35729"

postgres:
  image: postgres:9.5
  ports:
    - "5432"

bundle:
  image: tiny_api
  environment:
    BUNDLE_GEMFILE: /api/Gemfile
    BUNDLE_JOBS: 20
    BUNDLE_PATH: /bundle
  volumes:
    - /bundle
