default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: <%= ENV['POSTGRES_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_1_PORT_5432_TCP_PORT'] %>

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
